/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author ASUS
 */
public class VistaInstrucciones extends javax.swing.JFrame {

    VistaInstrucciones instrucciones;
    /**
     * Creates new form VistaInstruccion
     */
    public VistaInstrucciones() {
        setResizable(false);
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bComenzar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setText("simplemente debes dar click sobre tu pokemon.");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 223, -1, -1));

        jLabel34.setText("Al iniciar el juego, empiezas con 10 vidas, las cuales se irán disminuyendo ");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 252, -1, -1));

        jLabel35.setText("dependiendo de tus jugadas.");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 275, -1, -1));

        jLabel36.setText("Conociendo estas simples instrucciones, te dejamos y que empiece la lucha!");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 379, -1, -1));

        jLabel37.setText("Que la fuerza esté de tu lado...");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 408, -1, -1));

        jLabel38.setText("No podrás conocer que pokemon es tu oponente, solamente conocerás su");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 304, -1, -1));

        jLabel39.setText("cantidad de resistencia, pero, si adivinas que pokemon es tu oponente, nada");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 327, -1, -1));

        jLabel24.setText("Hola luchador! Bienvenido a la gran lucha Pokemon, estamos muy cerca");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 56, -1, -1));

        jLabel25.setText("del gran momento, solo debes conocer un poco sobre las reglas del");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 79, -1, -1));

        jLabel27.setText("juego, para que seas un gran luchador y le ganes a todos tus enemigos.");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 102, -1, -1));

        jLabel28.setText("Debes tener en cuenta que no eres tu quien escoge tu Pokemon, éste");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 131, -1, -1));

        jLabel29.setText("es seleccionado por nosotros, pero no te preocupes nos aseguraremos");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 154, -1, -1));

        jLabel31.setText("Puedes realizar dos acciones al estar en juego, atacar o defenderte, para");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 177, -1, -1));

        jLabel40.setText("más dale click al botón \"Yo sé quién eres!\".");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 350, -1, -1));

        jLabel32.setText("atacar debes dar click sobre el pokemon de tu oponente y para adefenderte");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel2.setText("Instrucciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        bComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/start_button_png_1310741 (1).png"))); // NOI18N
        bComenzar.setToolTipText("");
        bComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(bComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComenzarActionPerformed
        VistaArena arena =  new VistaArena();
        arena.setVisible(true);
        dispose();
    }//GEN-LAST:event_bComenzarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bComenzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    // End of variables declaration//GEN-END:variables
}
